# fly.toml app configuration file generated for morfars-stuga on 2023-07-13T16:03:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morfars-stuga"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
